### ISSUE TITLE
Can't open an existing runbook

### ISSUE THREAD

**Issue by 1trevor** [Maaaarden/VSCode-AzureAutomationExtension#11]
Is it possible to open an existing runbook so it can be edited instead of creating a new one?

**Comment by Maaaarden** [comment]
Hi - no this is not posible right now.

I will however note it down, and start looking in to the posibility of doing so.

**Comment by GoodbyeWorld** [comment]
This would be really helpful.

Also, more elaborate docs describing what we need to configure, and where to obtain those values.  For example, what's the "Client ID for your AAD App" intended to be?

**Comment by Maaaarden** [comment]
Hi - this issue has now been resolved in latest release 0.6.6

@GoodbyeWorld - please create another issue on this, and I will look into it.
