### ISSUE TITLE
Is debugging supported?

### ISSUE THREAD

**Issue by artisticcheese** [Maaaarden/VSCode-AzureAutomationExtension#21]
I don't see it's in a list of commands, is debugging of scripts supported?

**Comment by Maaaarden** [comment]
Not in the current version. 
All code execution is performed in Azure.

**Comment by Maaaarden** [comment]
@artisticcheese 

No current plans to try and implement full debugging. You can use the built in Powershell debugging, if you have the Powershell extension - at least for the parts that does not utilize Azure only functionality.
