### ISSUE TITLE
¸Support for python runbook

### ISSUE THREAD

**Issue by simonlegeek** [Maaaarden/VSCode-AzureAutomationExtension#27]
Hi,

Thanks for this very useful extension. Are you planning to add support for python runbook? I might simply be missing something, but the extension forces us to work with ps1 files and I don't feel I can save python runbook to Azure since I can't select the runbook type.

Thanks

**Comment by Maaaarden** [comment]
Hi @simonlegeek 

You are correct - the extension only supports regular Powershell runbooks right now.
Another user is requesting support for Powershell Workflow runbooks as well, and I've noted it down and will try and fit it into my schedule.

**Comment by Maaaarden** [comment]
Hi @simonlegeek 

Unfortunately, Microsoft doesn't support creation of Python runbooks via their API. Thus it is not possible for me to make this extension do so.

I've tried to reach out to Microsoft, and as soon as I hear something, I'll let you know.

**Comment by Maaaarden** [comment]
@simonlegeek 

Found a loophole - Python is now supported as of v0.9.0

Cheers

**Comment by simonlegeek** [comment]
Awesome, Thank you soo much!

Keep up the good work!
