### ISSUE TITLE
Could not get OAuth Token!

### ISSUE THREAD

**Issue by jlarrow** [Maaaarden/VSCode-AzureAutomationExtension#32]
"Could not get OAuth Token!" is the error I get.

I see in the change log there was an issue corrected for '+' ... are there perhaps other character issues?

My secret contains '+' and '/' and '=' (on the end).  Otherwise, they're all letters and numbers.

**Comment by Maaaarden** [comment]
Hi @jlarrow 

Hmm - must be something other than the '/' , my token contains both '+' and '/', as well as the '=' on the end.

Can you try POST in postman against the following url:

Replace 'tenantId' with your tenant id
https://login.microsoftonline.com/'tenantId'/oauth2/token?api-version=1.0

With the following body:

Replace 'clientId' and 'clientSecret' with your ID and your secret
grant_type=client_credentials&resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id='clientId'&client_secret='clientSecret`,


And remember to put in the following header:

'Content-Type': 'application/x-www-form-urlencoded'



Please return with a result, or fire away if you have any questions

**Comment by jlarrow** [comment]
Hello @Maaaarden

Sorry for the delay ... off work for a few days then offsite meeting most of today.
I think I did it right ... first time using postman:

# cat .\response.json
{"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: f5a3aee8-7bad-4bea-b07e-eb5ffb961600\r\nCorrelation ID: 2f73065a-b88e-4223-8778-cf445e3ddf44\r\nTimestamp: 2018-11-07 14:34:11Z","error_codes":[70002,50012],"timestamp":"2018-11-07 14:34:11Z","trace_id":"f5a3aee8-7bad-4bea-b07e-eb5ffb961600","correlation_id":"2f73065a-b88e-4223-8778-cf445e3ddf44"}

**Comment by Maaaarden** [comment]
Hi @jlarrow 

No worries - Well, it looks like you've got your secret wrong. 
Try going into you Azure App, and generate another secret to try with, and see if that helps.

**Comment by jlarrow** [comment]
I got my existing secret to work in postman by encoding it with:
```code
# [System.Web.HttpUtility]::UrlEncode($URL)
```
However, that same string configured in the extension doesn't seem to work.

**Comment by Maaaarden** [comment]
Where did you set the encoding you say?

**Comment by jlarrow** [comment]
sorry, I guess my snippet was a little miss-leading ... In PowerShell, I should've said $secret not $URL (I just cut/paste that.  I encoded the secret string and then postman worked.

I get:
```code
# cat .\response_when_encoded.json
{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"0","expires_on":"1541627421","not_before":"1541623521","resource":"https://management.core.windows.net/","access_token":"<DELETED>"}
```

**Comment by Maaaarden** [comment]
I've successfully tested a version now, with added encoding - thanks for pointing me in that direction.
v0.9.6 should be available anytime soon now, for you to test.

**Comment by jlarrow** [comment]
NP, glad to help.  Looks like a neat extension, I'm looking forward to giving it a try.

**Comment by Maaaarden** [comment]
@jlarrow 
Did you get it to work?

**Comment by jlarrow** [comment]
@Maaaarden,

No, I wasn't able to get it to work.  I'm running version v0.9.6.

I generated a new key.  This new key works raw **or** "UrlEncode"d in Postman — while I can't get the new key to work in the extension as either raw or "UrlEncode"d.

Anything more I can test to get more information?

Thanks

**Comment by Maaaarden** [comment]
@jlarrow Hmm - sounds a bit weird... What error pops up?

Client ID, Tenant ID etc is correct as well?

**Comment by jlarrow** [comment]
@Maaaarden,
Same error "Could not get OAuth Token!".
Yes, Client ID and Tenant ID are the same strings as what works with postman.

**Comment by Maaaarden** [comment]
@jlarrow 

If you try and Toggle Developer Tools (In the Help menu), and find the console, it should output the body of the response. Perhaps we can find the cause here.
