### ISSUE TITLE
Support AzAutomation DSC Configurations

### ISSUE THREAD

**Issue by JustinGrote** [Maaaarden/VSCode-AzureAutomationExtension#34]
In addition to runbooks, supporting DSC configurations would be nice.

Here's what I'm doing today with a tasks.json and Invoke-Build, same code could be integrated and progress shown using VSCode's integrated progress bar.

https://gist.github.com/JustinGrote/d29b886ed2e21a81b773b3fa7dda0d38

**Comment by Maaaarden** [comment]
Hi @JustinGrote 

Sorry for the lack of response on this matter.
There is no plans of adding DSC configurations to the extension.


Regards
