### ISSUE TITLE
Support for Azure AD use accounts

### ISSUE THREAD

**Issue by noendscripting** [Maaaarden/VSCode-AzureAutomationExtension#36]
Great extension.

But using Service Principal to manage runbooks breaks basic auditing and security requirements and thus I can neither use it nor recomend using this extension. ISE ADD-ON allows for  using user account in azure AD
https://github.com/azureautomation/azure-automation-ise-addon

**Comment by joshfria** [comment]
Second this. It would be valuable to sign in with our own accounts.

**Comment by Maaaarden** [comment]
Hi @noendscripting and @joshfria 

First, sorry for the lack of response on this matter.

That said - this functionality will not be looked into for now.
