### ISSUE TITLE
Support for Azure Gov

### ISSUE THREAD

**Issue by jsheehan6** [Maaaarden/VSCode-AzureAutomationExtension#41]
I love the idea of your Azure Automation extension so I can develop runbook code in VSCode. However, after installing the extension I am getting an error that the subscription is not found. Does the extension support Azure Gov? Apologies if I missed a release note about this.
![2020-05-01_9-44-29](https://user-images.githubusercontent.com/36737602/80809878-9e8fd800-8b90-11ea-9559-30fdc0f7606d.png)

**Comment by Maaaarden** [comment]
Hi @jsheehan6 

My apologies for not responding to this. 
I'm not currently aware of criteria for using Azure Gov. This is built against standard Microsoft API's, these might not be available for Azure Gov.

Regards
